# to build this docker image:
#   docker build -f Dockerfile.gpu .
FROM ghcr.io/hybridgroup/opencv:4.8.1-gpu-cuda-11 AS gocv-gpu

ENV GOPATH /go

COPY . /go/src/github.com/xuxiaoshuo/gocv/

WORKDIR /go/src/github.com/xuxiaoshuo/gocv
RUN go build -tags cuda -o /build/gocv_cuda_version ./cmd/cuda/

CMD ["/build/gocv_cuda_version"]
